### ISSUE TITLE
NullReferenceException in GetSentiment since version 1.0.2.x

### ISSUE THREAD

**Issue by ThisWillDoIt** [adgroc/Cognitive-TextAnalytics-Windows#24]
Calling GetSentiment or GetSentimentAsync results in NullReferenceExceptions in every currently available NuGet version 1.0.2.x

The same code works in 1.0.1.x versions.

Minimal working example: https://github.com/ThisWillDoIt/ProjectOxfordBug

**Comment by adgroc** [comment]
Bypassed supported language validation if a language is not provided. Available in version [1.0.4.x](http://www.nuget.org/packages/Microsoft.ProjectOxford.Text/1.0.4.29051).
